include:
   - project: 'build_server/gitlab_ci_includes'
     ref: 'master'
     file: 'projects/vrlab.yml'

#function to install dependencies (before_script also allies to includes)
.dep_install: &dep_install |
  apt-get install -y libprotobuf-dev protobuf-compiler libzmqpp-dev
  ./install_dependencies.sh .
  . env.sh
  mkdir build
  cd build

build_standalone:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
  stage: build
  script:
    - *dep_install
    - cmake ..
    - make -j

test_standalone:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
  stage: test
  script:
    - *dep_install
    - cmake -D ROCK_TEST_ENABLED=ON ..
    - make -j
    - ./test/test_suite

