include:
   - project: 'build_server/gitlab_ci_includes'
     ref: 'master'
     file: 'projects/vrlab.yml'


image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
before_script: 
  - apt-get install -y libprotobuf-dev protobuf-compiler libzmqpp-dev
  - ./install_dependencies.sh .
  - . env.sh
  - mkdir build
  - cd build

build_standalone:
  stage: build
  script:
    - cmake ..
    - make

test_standalone:
  stage: test
  script:
    - cmake -D ROCK_TEST_ENABLED=ON ..
    - make
    - ./test/test_suite

