include:
   - project: 'build_server/gitlab_ci_includes'
     ref: 'master'
     file: 'projects/vrlab.yml'


image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
before_script: 
  - apt-get install -y libprotobuf-dev protobuf-compiler libzmqpp-dev
  - ./install_dependencies.sh .

build:
  stage: build
  script:
    - . env.sh
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - ls -la #need to build here?
    - . env.sh
    - mkdir build
    - cd build
    - cmake -D ROCK_TEST_ENABLED=ON ..
    - make
    - ./test/test_suite

