version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get install -y build-essential libprotobuf-dev protobuf-compiler libzmqpp-dev
      - run: ./install_source_dependencies.sh .
      - run: . env.sh
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make -j

#test_standalone:
#  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
#  stage: test
#  script:
#    - *dep_install
#    - cmake -D ROCK_TEST_ENABLED=ON ..
#    - make -j
#    - ./test/test_suite
