version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential git cmake pkg-config libboost-test-dev libboost-system-dev
libprotobuf-dev protobuf-compiler libzmqpp-dev
      - run: ./install_source_dependencies.sh ./external
      - run: mkdir build
      - run: . env.sh && cd build && cmake -D ROCK_TEST_ENABLED=ON ..
      - run: make -j -C build/
      - run: . env.sh && ./build/test/test_suite
