version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential git cmake pkg-config libprotobuf-dev protobuf-compiler libzmqpp-dev
      - run: ./install_source_dependencies.sh ./external
      - run: mkdir build
      - run: . env.sh && cd build && cmake -D ROCK_TEST_ENABLED=ON ..
      - run: make -j -C build/
      - run: . env.sh && .build/test/test_suite

#test_standalone:
#  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-build_essentials_ubuntu:latest
#  stage: test
#  script:
#    - *dep_install
#    - cmake -D ROCK_TEST_ENABLED=ON ..
#    - make -j
#    - ./test/test_suite
