version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: ./.circleci/prepare_build.sh
      - run: make -j -C build/

  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: ./.circleci/prepare_build.sh
      - run: make -j -C build/
      - run: make -j -C build/ test_suite
      - run: . env.sh && ./build/test/test_suite

workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test
